# Generated by Django 5.1.6 on 2025-02-17 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('thirdname', models.CharField(max_length=100)),
                ('number_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.groups')),
            ],
        ),
    ]
