# Generated by Django 5.1.6 on 2025-02-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
