# Generated by Django 5.1.6 on 2025-03-08 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
