# Generated by Django 5.1.6 on 2025-03-08 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_students_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='role_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.role'),
        ),
    ]
