# Generated by Django 5.1.6 on 2025-03-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_role_students_role_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='role_student',
            new_name='name_role_for_student',
        ),
    ]
