# Generated by Django 5.1.6 on 2025-03-08 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_rename_role_student_students_name_role_for_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='name_role_for_student',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
